export const ROUTES = {
  REGISTER: '/',
  LOGIN: '/login',
  HOME: '/home',
  QUIZ_INFO: '/quiz-info',
  BUSCA: '/busca',
  SOBRE: '/sobre',
  QUIZ: '/quiz',
  QUIZ_RESULTADO: '/quiz/resultado',
  BUSCA_FACULDADES: '/busca/faculdades',
  BUSCA_CURSOS: '/busca/cursos',
  BUSCA_CHATBOT: '/busca/chatbot',
  CURSO_DETAIL: '/busca/:id/curso',
  FACULDADE_DETAIL: '/busca/:id/faculdade',
  PROFILE: '/profile',
  PROFILE_CAPELINHOS: '/profile/capelinhos',
  PROFILE_HISTORICO: '/profile/historico',
  PROFILE_EDITAR: '/profile/editar',
} as const;
